### ISSUE TITLE
Allow expressions in max_concurrency attribute

### ISSUE THREAD

**Issue by e-gineer** [turbot/flowpipe#810] opened 2024-03-19 00:58 UTC
I have an input step with `max_concurrency` set:
```hcl
     max_concurrency = param.parallel ? null : 1
```

But unfortunately it fails to parse, with error:
```
~/src/flowpipe-mod-approval $ flowpipe pipeline list
Error: Internal Error: Failed to decode mod: Expression not allowed in max_concurrency
(/Users/nathan/src/flowpipe-mod-approval/mod.fp:56,5-48)
```

**Comment by vhadianto** [comment] 2024-03-25 13:26
Duplicate of #800

**Closed by vhadianto** 2024-03-25 13:26 UTC
Labels: duplicate, enhancement
