### ISSUE TITLE
Does max_concurrency work for a pipeline step?

### ISSUE THREAD

**Issue by e-gineer** [turbot/flowpipe#815] opened 2024-03-26 11:09 UTC
Version: v0.4.2

```
  step "pipeline" "approve" {
    for_each = param.approvers

    max_concurrency = 1

    pipeline = pipeline.single_approval

    args = {
      approver = each.value
      subject = param.subject
      prompt = param.prompt
      timeout = param.timeout
      default_decision = param.default_decision
    }
  }
```

I believe that the pipeline step does not respect max_concurrency? It is triggering my child pipeline multiple times in parallel even if I have max_concurrency set to 1.

Also - it's hard to debug / tell ... because the verbose output does not display the value of the max_concurrency arg?

```
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[0]] Starting pipeline
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[0]] Arg args = {
  "approver": "foo",
  "default_decision": false,
  "prompt": "Should I square 2?",
  "subject": "Should I square 2?",
  "timeout": 10
}
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[0]] Arg pipeline = approval.pipeline.single_approval
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[1]] Starting pipeline
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[1]] Arg args = {
  "approver": "bar",
  "default_decision": false,
  "prompt": "Should I square 2?",
  "subject": "Should I square 2?",
  "timeout": 10
}
2024-03-26 07:05:24 exec_co1ant4o47mg84ftbg8g [approve.approve[1]] Arg pipeline = approval.pipeline.single_approval
```

**Comment by vhadianto** [comment] 2024-03-27 06:06
Bug caused by async execution of nested pipeline.

**Comment by vhadianto** [comment] 2024-04-12 11:58
Fixed in v0.4.3

**Closed by vhadianto** 2024-04-12 11:58 UTC
Labels: bug
